version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

